### ISSUE TITLE
Is it possible to create Bindings to properties ?

### ISSUE THREAD

**Issue by kaosat-dev** [jkb0o/belly#33]
Hello again !

Is it currently possible to do bindings to properties directly ? (ie not in a for loop)
More specifically I was looking for a way to control the `display` property with a binding (to selectively hide some parts of the ui, ie for tabs etc)

I have tried a few different things without success, sorry again if I missed something obvious :)

`<div bind:display={from!(ui_state:active_tab|fmt.c("none"))}>"OTHER text"</div>`
I am guessing that one does not work as `display' is not a component but a field of "Style"

So I also tried
 `<div bind:s:display={from!(ui_state:active_tab|fmt.c("none"))}>"OTHER text"</div>`
and some things like
`<div bind:s:background-color={from!(ui_state:active_tab|fmt.c("#9c27b0"))}>"BLA OTHER text"</div>`

And various other things (with & without format , with `String` fields to bind to etc), 
without success.

 this works one I can switch between flex & none, but is not bound to anything, obviously (code shortened), so nothing dynamic 
`let display_test = "none";  <div s:display={display_test}>"some text"</div>`

Thanks in advance !

**Comment by jkb0o** [comment]
`s:display` is a style style property. It is controlled by the `ess` system (stylesheets affects the target values if no `s:display` provided).
What you can do is to bind the property of your component to `Style.dispaly` property:

```rust
struct UiState {
  active_tab: Display
}
fn setup(mut commands: Commands) {
  let entity = commands.spawn(UiState).id();
  let span = commands.spawn_empty().id();
  commands.add(
    from!(entity, UiState:active_tab) >> to!(span,Style:display)
  );
  commands.add(eml! {
    <body>
      <span {span} s:display=managed() s:width="100px" s:height="100px" s:bacground-color="white"/>
  });
```
Now every time you change `UiState.active_tab` property, the `Style.display` changed. Note the `s:display=managed()` part. It means that you won't `ess` changes `Style.display` for `span` label, because you manage it by yourself.

## However

I'm not sure what you want to achieve, but binding to style properties is not what you want in most cases. Looks like you need to add some class to element (`hidden` for example) when you want to hide it. You can inspect the https://github.com/jkb0o/belly/blob/main/examples/elements-modification.rs example to see how it can be done.

If you trying to implement something like tabview, my advance is to use `btngroup`. You can look how to use it in the https://github.com/jkb0o/belly/blob/main/examples/image.rs 

For now the only way to react on `btngroup.value` changes is to write your own system:

```rust
#[derive(Component, Default)]
struct TabController;

fn setup(mut commands: Commands) {
  commands.addc(StyleSheet::parse(r#"
    .hidden {
      display: none;
    }
  "#);
  commands.add(eml! {
    <body>
      <btngroup with=TabController>
        <button value=".tab1" pressed>Tab 1</button>
        <button value=".tab2">Tab 2</button>
        <button value=".tab3">Tab 3</button>
      </btngroup>
      <div c:content>
        <div c:tab1>Tab 1 content</div>
        <div c:tab c:hidden>Tab 2 content</div>
        <div c:tab3 c:hidden>Tab 3 content</div>
      </div>
    </body>
  })
}

fn process_tabs(
  elements: Elements,
  tabs: Query<&BtnGroup, (With<TabController>, Changed<BtnGroup>)>
) {
  for tab in tabs.iter() {
    // add hidden to all divs inside content
    elements.select(".content > *").add_class("hidden")
    // remove hidden from class provided by btngroup.value, which is .tab1, .tab2 or .tab3
    elements.select(tab.value).remove_class("hidden")
  }
}
```

When I add `changed` signal to btn group it will be even simpler.

**Comment by jkb0o** [comment]
@kaosat-dev 
I've just pushed `on:value_change` implementation, now the tabview (https://github.com/jkb0o/belly/blob/main/examples/tabview.rs) ie even simpler:
```rust
// examples/tabview.rs
// cargo run --example tabview
use belly::prelude::*;
use bevy::prelude::*;

fn main() {
    App::new()
        .add_plugins(DefaultPlugins)
        .add_plugin(BellyPlugin)
        .add_startup_system(setup)
        .run();
}

#[derive(Component, Default)]
struct TabController;
fn setup(mut commands: Commands) {
    commands.spawn(Camera2dBundle::default());
    commands.add(StyleSheet::parse(
        "
        .hidden {
            display: none;
        }
    ",
    ));
    commands.add(eml! {
      <body s:padding="20px">
        <buttongroup on:value_change=connect!(|ctx| {
            let ev = ctx.event();
            ctx.select(ev.old_value()).add_class("hidden");
            ctx.select(ev.new_value()).remove_class("hidden");
        })>
          <button value=".tab1" pressed>"Tab 1"</button>
          <button value=".tab2">"Tab 2"</button>
          <button value=".tab3">"Tab 3"</button>
        </buttongroup>
        <br/>
        <div c:content>
          <div c:tab1>"Tab 1 content"</div>
          <div c:tab2 c:hidden>"Tab 2 content"</div>
          <div c:tab3 c:hidden>"Tab 3 content"</div>
        </div>
      </body>
    });
}
```

**Comment by jkb0o** [comment]
This will be done right in `polako` (#77)
