### ISSUE TITLE
Not compatibly with bevy-inspector-egui@0.18.1

### ISSUE THREAD

**Issue by teken** [jkb0o/belly#53]
There is a conflict with the syn package

**Comment by jkb0o** [comment]
Hi there! `belly` didn't migrate to `bevy@0.10` because of ui bugs in the bevy. `bevy-inspector-egui@0.18.1` is targeting `bevy@0.10`, this is why you got conflicts. Once `bevy` release `0.10.1`, I'll migrate `belly`.

There is a https://github.com/jkb0o/belly/tree/bevy-0.10 wip-branch that points custom commit in bevy (0.10 + ui fixes) in your cargo.toml, but you probably will get yet another conflicts.
