### ISSUE TITLE
Bevy 0.10 support?

### ISSUE THREAD

**Issue by mlp1802** [jkb0o/belly#54]
Will this be available for bevy 0.10?

**Comment by jkb0o** [comment]
Hi there! `belly` didn't migrate to `bevy@0.10` because of ui bugs in the bevy. Once `bevy` release `0.10.1`, I'll migrate `belly`.

There is a https://github.com/jkb0o/belly/tree/bevy-0.10 (#51 ) wip-branch that points custom commit in bevy (0.10 + ui fixes) in your cargo.toml, but I'm not sure it can be build without conflitcs unless you pin the exactly same bevy version in your cargo.

**Comment by mlp1802** [comment]
Alright, great news! This is a very promising project
